{% set name = "sawyer" %}
{% set version = "0.9.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: fa3a72d62a4525517b18857ddb78926aab3424de0129be6772a8e2ba240e7aca

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-addressable >=2.3.5
    - rb-faraday >0.8,<2.0

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Secret User Agent of HTTP

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/lostisland/{{ name }}

extra:
  recipe-maintainers:
    - sodre
