travis:
  secure:
    BINSTAR_TOKEN: vyzZnVupOr+4bVscHZuC6L33fgqWjilh6IxCBvbM5cLbinCA0VFRQqklFQLSD1L2mEESTZGiCc2K1pbUK10DYxYGWwNdcwWY+F7cKTsgt7R+Q2YwFL/xoiHPT3Uz+O+9EUlOtZBOlNOS+VGzfqzSeSaAXftkuiTSJ3APsBu/w1NRQh00nsv1DQJ+JvkqwlLbOf5wTkY20pLAZwLSErh8c5dKnrzKnsq5Axr1fPjIr2PssXguftz50OUwnOBqSnU/ekb8dZXOpdrWJVUFBBmPApcxGmfYU4/I1UFuZ4ztzT7hswmr/ZJsL3wtrMdTQ50O6sq5weIL9FVHcbvAEuUuctS1M5qlEB67D8ZVvgkpZHn34OpWYZV+1LPhsjsMwimI1X6CJ+QTbHMfvCYcbjvntnrVSqs4OWsoy47hRX3Qp8Qb4IKBSu+k4XxnBh87okRFFRA8TrL0hmqiy/v/P9J9UOE1M9VymTLemyjRwQQJplGmy9auQttT0IMiHhlD4cttC1KlW4yeyqSLQzxOSU4D43/JY7dtVZxwS3UdyCD5SANSzPe7z+uamM8CLmtC2SgxIedWvf0MSBZG3mfUKRghwrm/YSl1OwO+UTKWp1sP5T0o1NMURvo/whIjXOudjRdfbjEaRQajYigseF09LZilsf2JObk4PaWHcfp2LCs6GrM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
